openapi: 3.0.0
info:
  title: Peeringhub API
  description: Optional multiline or single-line description in HTML.
  version: 1.0.0
  #servers:
  # Added by API Auto Mocking Plugin
#  - description: SwaggerHub API Auto Mocking
#    url: https://virtserver.swaggerhub.com/araqelyan777/Peeringhub/1.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: http://localhost:8080/
paths:
  /admin/clec/{clec_uuid}:
    get:
      tags:
        - Admin API
      description: Get Clec User
      parameters:
        - name: clec_uuid
          in: path
          description: Clec uuid to get clec user
          required: true
          schema:
            type: string
#      security:
#        - authorization: [ ]
      responses:
        200:
          description: Successfully Executed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserClec'
#        401:
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Unauthenticated'
#          description: Unauthenticated
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectNotFound'
          description: Object not found error
  /admin/clec:
    post:
      tags:
        - Admin API
      description: Create Clec User
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: string
                clec_uuid:
                  type: string
                  format: uuid
                  example: d835c2f0-a2e3-4a6f-b973-e7e40a85d35a
                password:
                  type: string
                  format: password
                  example: password
                confirm_password:
                  type: string
                  format: password
                  example: password
                email:
                  type: string
                  format: email
                  example: admin@gmail.com
                role:
                  type: string
                  example: clec
                first_name:
                  type: string
                  example: string
                last_name:
                  type: string
                  example: string
                phone_number:
                  type: string
                  example: string
                contact_address:
                  type: string
                  example: string
                contact_suite:
                  type: string
                  example: string
                contact_city:
                  type: string
                  example: string
                contact_country:
                  type: string
                  example: string
                contact_postal_code:
                  type: string
                  example: '0008'
                company_name:
                  type: string
                  example: string
                profile_address:
                  type: string
                  example: string
                profile_suite:
                  type: string
                  example: string
                profile_city:
                  type: string
                  example: string
                profile_country:
                  type: string
                  example: string
                profile_postal_code:
                  type: string
                  example: '8000'
                state_of_clec_certification:
                  type: string
                  example: US
                ocn:
                  type: array
                  example: [ test, te75, 7895 ]
                upload_clec_certification:
                  type: array
                  items:
                    type: string
                    format: binary
              required:
                - username
                - clec_uuid
                - password
                - confirm_password
                - email
                - role
                - first_name
                - last_name
                - phone_number
                - contact_address
                - contact_suite
                - contact_city
                - contact_country
                - contact_postal_code
                - company_name
                - profile_address
                - profile_suite
                - profile_city
                - profile_country
                - profile_postal_code
                - state_of_clec_certification
                - upload_clec_certification
                - ocn
      responses:
        200:
          description: Successfully Executed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  object_id:
                    type: string
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: Validation error
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectNotFound'
          description: Object not fount error
        406:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlreadyExists'
          description: User already exists

components:
  securitySchemes:
    authorization: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
      name: authorization
      in: header
      description: 'Name: authorization'

  schemas:
    UserClec:
      properties:
        payload:
          items:
            type: object
            properties:
              username:
                type: string
              clec_uuid:
                type: string
                format: uuid
              password:
                type: string
                format: password
              email:
                type: string
                format: email
              role:
                type: string
              first_name:
                type: string
              last_name:
                type: string
              phone_number:
                type: string
              contact_address:
                type: string
              contact_suite:
                type: string
              contact_city:
                type: string
              contact_country:
                type: string
              contact_postal_code:
                type: number
              company_name:
                type: string
              profile_address:
                type: string
              profile_suite:
                type: string
              profile_city:
                type: string
              profile_country:
                type: string
              profile_postal_code:
                type: number
              state_of_clec_certification:
                type: string
                example: US
              upload_clec_certification:
                type: string
              ocn:
                type: array
                example: [test, te75, 7895]
        success:
          type: boolean
          default: true
        token:
          type: string
        expired:
          type: string
          example: 2 days
    ObjectNotFound:
      properties:
        error:
          type: string
        error_type:
          type: string
        success:
          type: boolean
          default: false
    ValidationError:
      properties:
        error_type:
          type: string
        success:
          type: boolean
          default: false
        error:
          type: array
          items:
            type: object
            items:
              type: string
    AlreadyExists:
      properties:
        error_type:
          type: string
        success:
          type: boolean
          default: false
        error:
          properties:
            message:
              type: string
            code:
              type: number
              default: 0
    Unauthenticated:
      properties:
        error_type:
          type: string
        success:
          type: boolean
          example: false
        error:
          properties:
            message:
              type: string
            code:
              type: number
              default: 0








